REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_PASSWORD = None
REDIS_KEY = 'proxy'

MAX_SCORE = 100.0
MIN_SCORE = 0
INITIAL_SCORE = 10

POOL_UPPER_THRESSHOLD = 10000

VALID_STATUS_CODE = [200, 302]
TEST_URL = 'https://www.lagou.com'

TESTER_CYCLE = 20
GETTER_CYCLE = 300

TESTER_ENABLED = True
GETTER_ENABLED = False
API_ENABLED = True

BATCH_TEST_SIZE = 10
